spring:
  thymeleaf:
    cache: false
    
server:
  context-path: /api
    
logging:
  level:
    org.springframework.web.client: TRACE
    org.springframework.http.client: TRACE
    org.springframework.security: DEBUG