spring:
  thymeleaf:
    cache: false

server:
  port: 8082

logging:
  level:
    org.springframework.web.client: TRACE
    org.springframework.http.client: TRACE
    org.springframework.security: DEBUG